import {StyleSheet} from 'react-native';
import {
  dW,
  dH,
  windowHeight,
  windowWidth,
} from '../../utils/dynamicHeightWidth';
import assets from '../../assests/images/index';
import colors from '../../constants/colors';
const useStyle = () => {
  return StyleSheet.create({
    header_img: {height: 200, width: '100%'},
    imageBack: {
      width: '100%',
      height: '100%',
    },
    padding_20: {
      paddingHorizontal: 22,
      marginTop: 20,
    },
    FlatList: {paddingHorizontal: 0, paddingBottom: 30},
    header_c: {
      flex: 1,
      backgroundColor: colors.black,
    },
    image: {height: 140, width: '100%'},
    heading: {
      marginTop: dW(20),
      textAlign: 'left',
      margin: 20,
      fontFamily: 'Montserrat-Bold',
      color: colors.white,
      fontSize: dW(16),
      letterSpacing: 1,
    },
    heading3: {
      marginTop: dW(20),
      textAlign: 'left',

      fontFamily: 'Montserrat-Bold',
      color: colors.white,
      fontSize: dW(16),
      letterSpacing: 1,
    },
    center: {
      //  backgroundColor: 'red',
      alignContent: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 20,
    },
    manfoot: {
      marginRight: 20,
      marginLeft: 20,
      borderRadius: 10,
      alignSelf: 'center',
      height: 160,
      width: '91%',
      // marginTop: 65,
      alignItems: 'center',
      justifyContent: 'center',
    },
    foot: {
      //marginRight: 10,
      borderRadius: 10,
      //  position: 'absolute',
      height: 160,
      width: '100%',
      // marginTop: -80,
    },
    blackv: {
      alignSelf: 'flex-end',
      margin: 15,
      height: 30,
      paddingHorizontal: 15,
      //  backgroundColor: colors.black,
      backgroundColor: 'transparent',
      borderRadius: 5,
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
    },
    blackvHeading: {
      //  marginTop: dW(20),
      textAlign: 'left',
      // margin: 20,
      fontFamily: 'Montserrat-SemiBold',
      color: colors.white,
      fontSize: dW(12),
      letterSpacing: 1,
    },
    downarrow: {height: 10, width: 10, resizeMode: 'contain', marginLeft: 6},
    save: {height: 28, width: 28, resizeMode: 'contain', marginTop: dW(20)},
    today: {
      marginTop: dW(7),
      textAlign: 'left',
      marginLeft: 20,
      fontFamily: 'Montserrat-Bold',
      color: colors.white,
      fontSize: dW(15),
      letterSpacing: 1,
    },
    start: {
      width: '90%',
      // marginTop: dW(5),
      textAlign: 'left',
      marginLeft: 20,
      fontFamily: 'Montserrat-Regular',
      color: colors.white,
      fontSize: dW(12),
      letterSpacing: 0,
      lineHeight: 25,
    },
    star: {
      alignSelf: 'flex-start',
      margin: 7,
      height: 28,
      paddingHorizontal: 10,
      marginLeft: 20,
      backgroundColor: colors.black,
      borderRadius: 13,
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
    },
    img_star: {height: 20, width: 20, resizeMode: 'contain'},
    two: {
      textAlign: 'left',
      fontFamily: 'Montserrat-SemiBold',
      color: colors.white,
      fontSize: dW(12),
      letterSpacing: 1,
    },
    center_1: {
      flex: 1,
      marginTop: 100,
      flexDirection: 'row',
      //paddingVertical: 15,
      alignItems: 'center',
      justifyContent: 'center',
      // backgroundColor: 'red',
    },
    flex_46: {
      marginLeft: 7,
      flex: 0.46,
      height: 130,
      padding: 10,
      borderTopLeftRadius: 10,
      borderTopRightRadius: 10,

      alignItems: 'center',
      justifyContent: 'center',
    },
    flex_48: {
      marginLeft: 1,
      flex: 0.45,
      height: 130,

      paddingHorizontal: 14,
      borderTopLeftRadius: 10,
      borderTopRightRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    img1: {
      borderRadius: 10,
      alignSelf: 'center',
      height: 110,
      //   padding: 20,
      width: '99%',
      // backgroundColor: colors.gray,
      alignItems: 'center',
      justifyContent: 'center',
    },
    img10: {
      borderRadius: 7,
      alignSelf: 'center',
      height: 110,
      //   padding: 20,
      width: '110%',
      // backgroundColor: colors.gray,
      alignItems: 'center',
      justifyContent: 'center',
    },
    img2: {
      marginRight: 10,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      height: 120,
      width: '99%',
      // marginTop: -80,
    },
    warm: {
      marginTop: dW(0),
      textAlign: 'center',
      marginLeft: 0,
      fontFamily: 'Montserrat-Bold',
      color: colors.white,
      fontSize: dW(16),
      letterSpacing: 1,
    },
    img3: {
      marginLeft: 0,
      borderRadius: 10,
      alignSelf: 'center',
      height: 120,
      width: '95%',
      // marginTop: -80,
      alignItems: 'center',
      justifyContent: 'center',
    },
    img4: {
      //marginRight: 10,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      height: 120,
      width: '100%',
      // marginTop: -80,
    },
    text: {
      marginTop: dW(0),
      textAlign: 'center',
      marginLeft: 20,
      fontFamily: 'Montserrat-Bold',
      color: colors.white,
      fontSize: dW(16),
      letterSpacing: 1,
    },
    main: {
      // height: 290,
      flex: 1,
      // marginTop: -20,
      justifyContent: 'center',
      borderRadius: 10,
      //paddingLeft: 10,
      alignContent: 'center',
      // backgroundColor: colors.blackshade,
    },
    padding: {paddingHorizontal: 20, borderRadius: 20},

    cc: {
      //marginTop: 10,
      paddingHorizontal: 15,
      paddingVertical: 12,
      //height: 190,
      // borderRadius: 10,

      backgroundColor: colors.blackshade,
    },
    flex_row: {flexDirection: 'row', justifyContent: 'space-between'},
    heading1: {
      marginTop: dW(0),
      textAlign: 'left',
      // marginLeft: 20,
      fontFamily: 'Montserrat-Bold',
      color: colors.white,
      fontSize: dW(14),
      //letterSpacing: 1,
    },
    heading2: {
      marginTop: dW(0),
      textAlign: 'left',
      // marginLeft: 20,
      fontFamily: 'Montserrat-SemiBold',
      color: colors.gray,
      fontSize: dW(13),
      // letterSpacing: 1,
    },
    padding_fl: {paddingHorizontal: 10, borderRadius: 20},
    contentContainerStyle: {
      padding: 10,
      borderRadius: 10,
    },
    paddgin_20: {paddingHorizontal: 20, marginTop: -10},
    flexD: {flexDirection: 'row', justifyContent: 'space-between'},
    style: {paddingVertical: 10, borderRadius: 20},
    ccc: {
      padding: 10,
      borderRadius: 10,
    },
    items: {
      height: 100,
      width: 80,
      marginLeft: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    man: {
      height: 60,
      width: 60,
      borderRadius: 30,
      borderWidth: 1,
      borderColor: colors.white,
      resizeMode: 'cover',
    },
    h1: {
      marginTop: dW(0),
      textAlign: 'center',
      fontFamily: 'Montserrat-SemiBold',
      color: colors.white,
      fontSize: dW(12),
    },
    coaches: {
      height: 80,
      flexDirection: 'row',
      marginTop: 10,
      borderRadius: 10,
      borderBottomColor: colors.gray,
      borderBottomWidth: 0.5,
    },
    coachess: {
      width: '75%',
      marginLeft: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    coaches_heading: {
      marginTop: dW(0),
      textAlign: 'left',
      // marginLeft: 20,
      fontFamily: 'Montserrat-Regular',
      color: colors.orange,
      fontSize: dW(11),
      letterSpacing: 1,
    },
    h6: {
      marginTop: dW(5),
      textAlign: 'left',
      marginRight: 20,
      fontFamily: 'Montserrat-SemiBold',
      color: colors.white,
      fontSize: dW(12),
      letterSpacing: 1,
    },
    img_70: {
      height: 70,
      width: 70,
      borderRadius: 5,
    },
    exe_view: {
      height: 50,
      flexDirection: 'row',
      marginTop: 5,
      backgroundColor: colors.blackShade_s,
      borderRadius: 10,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 7,
      },
      shadowOpacity: 0.43,
      shadowRadius: 9.51,

      elevation: 15,
    },
    exe_img: {
      height: 50,
      width: 60,
      borderTopLeftRadius: 10,
      borderBottomLeftRadius: 10,
    },
    flex_60: {
      // backgroundColor: 'red',
      width: '73%',
      marginLeft: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    h7: {
      marginTop: dW(0),
      textAlign: 'left',
      // marginLeft: 20,
      fontFamily: 'Montserrat-Bold',
      color: colors.white,
      fontSize: dW(12),
      letterSpacing: 1,
    },
    mint: {
      marginTop: dW(0),
      textAlign: 'left',
      // marginLeft: 20,
      fontFamily: 'Montserrat-Regular',
      color: colors.white,
      fontSize: dW(11),
      letterSpacing: 1,
    },
    arrowgray: {
      resizeMode: 'contain',
      height: 10,
      margin: 4,
      width: 10,
    },
    arrow: {
      resizeMode: 'contain',
      height: 14,
      width: 14,
      transform: [{rotate: '270deg'}],
    },
  });
};
export default useStyle;
