import React, {useState, useEffect, useRef} from 'react';
import {
  SafeAreaView,
  View,
  Image,
  Platform,
  ImageBackground,
  Text,
  StyleSheet,
} from 'react-native';
const strings = {
  empty: '',
  nosports: 'No sports ',
  coach: 'Coach',
  athletew: 'Athlete',
  rpe: 'RPE',
  time: 'TIME',
  DONE: 'DONE',
  leanv: 'Explore training and coaching tips',
  created_at: 'created_at',
  messages: 'Messages',
  messages_collection: 'Messages_Collection',
  sportsData: [
    {
      img: require('../assests/images/foot.png'),
      name: 'Basketball',
    },
    {
      img: require('../assests/images/faceB.png'),
      name: 'Football',
    },
    {
      img: require('../assests/images/scorrer.png'),
      name: 'Soccer',
    },
    {
      img: require('../assests/images/lac.png'),
      name: 'Lacrosse',
    },
    {
      img: require('../assests/images/baseball.png'),
      name: 'Baseball',
    },
  ],
  GAMES: ['Basketball', 'Football', 'Soccer', 'Lacrosse', 'Baseball'],
  two: 'Manage your team all in one place. Direct message your coach and stay up to date with the team in your team feed.',
  three:
    'Watch educational videos on your sport, tips and tricks from your coach, and explore bonus workouts.',
  imparent: 'I’m a Parent',
  imcoach: 'I’m a Coach',
  imathelete: 'I’m an Athlete',
  temand: 'Team and Coach Messaging',
  mobility: 'Daily Mobility',
  annualy: 'ANNUALY SUBSCRIPTION',
  monthly: 'MONTHLY SUBSCRIPTION',
  one: 'Based on your chosen sport you’ll be given daily mobility, warm up, and postgame exercises to stay active everyday.',
  Athletes: 'Athletes',
  lower: 'Subscribe to',
  UnstoppableAth: 'Unstoppable Athlete',
  by: 'By creating an account I agree I am over 13 year of age and agree with the',
  by1: ' Privacy Policy and Terms and Conditions',
  programs: 'Programs',
  teamfeed: 'Team Feed',
  editteam: 'Edit Team',
  coach_corner: 'Coaches Corner',
  infolook: 'Does this information look',
  correct: 'correct?',
  CONFIRM: 'CONFIRM',
  NEXT: 'NEXT',
  saved_videos: 'Saved Videos',
  saved_workouts: 'Saved Workouts',
  mark_complete: 'Mark Complete',
  completed: 'Completed',
  terms_condition: 'Terms and Conditions',
  complete_workout: 'Completed Workouts',
  choose_your_sport:
    '  Choose your sports from the list below, you can always change it later.',
  choosecoach: 'What sports do you coach?',
  choosesport: 'What sports do you play?',
  always: 'always edit this later.',

  SIGNIN: 'SIGN IN',
  athelete: [
    'Athelete#1',
    'Athelete#2',
    'Athelete#3',
    'Athelete#4',
    'Athelete#5',
  ],
  exp: 'Explore',
  confirmathe:
    '  Confirm the profile is yours and looks correct. You can edit or add any information as needed.',
  explore:
    'Explore programs, improve your skills, and prevent injury in any sport.',
  createacc: 'Create Account',
  CREATE_ACC: 'CREATE ACCOUNT',
  howmany: 'How many athletes are',
  createacconce: ' Create one',
  forgotPassword: 'Forgot Password',
  FoundProfile: 'We Found a Profile',
  AGE: 'AGE',
  suggested: 'Suggested',
  regsiter: 'you registering?',
  donthave: 'Don’t have an account?',
  Unstoppable: 'Unstoppable',
  myteam: 'My Team',
  myprog: 'My Programs',
  mysche: 'My Schedule',
  mymess: 'My Messages',
  invitecoach: 'Invite My Coach',
  inviteyourcoach: 'Invite Your Coach',
  log: 'Log Out',
  being: '  Begin messaging, training and more.',
  sharecode: 'SHARE CODE',
  skip: ' Skip, I’ll do it later',
  learnv: 'Explore training and coaching tips',
  justcode:
    'Just share this code with your coach and ask them to signup with the code, once they’re in the app you can message each other and explore their coaching.',
  editprofile: 'Edit Profile',
  ableback: 'You won’t be able to get it back.',
  willmiss: 'We’ll miss you!',
  LOGOUT: 'LOGOUT',
  deleteacc: 'Delete Account',
  deleconfirm: 'Are you sure you want to delete your account?',
  Enter_Athelete: 'Enter Athlete',
  fname: 'FIRST NAME',
  lname: 'LAST NAME',
  SAVE: 'SAVE',
  UPDATE: 'UPDATE',
  CANCEL: 'CANCEL',
  GENDER: 'GENDER',
  change: 'CHANGE PHOTO',
  entercode: 'Enter Your Code',
  enterteam: 'Enter Your Team',
  uploadfile: 'Upload File',
  entercode_des:
    '   Enter the code your parent or coach provided you. If you have an xisting account, you will need to confirm your information is correct.',
  logingout: 'Logging out?',
  SPORTS: 'SPORTS',
  CHOOSE_MU: 'You can choose multiple and can',
  findchat: 'Find Chats',
  findUser: 'Find User',
  directmsg: 'Direct Messages',
  Schedule: 'My Schedule',
  newchat: 'New Chat',
  login: 'Login',
  team: 'Team',
  get_started: 'GET STARTED',
  ihaveacode: 'I HAVE A CODE',
};
export default strings;
