import {StyleSheet} from 'react-native';
import {dW, dH, windowHeight, windowWidth} from '../utils/dynamicHeightWidth';
import colors from '../constants/colors';
const useStyle = () => {
  return StyleSheet.create({
    bottomSheet_btn: {
      backgroundColor: colors.primary,
      width: '100%',
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 8,
    },
    BottomSheet_container: {
      alignItems: 'center',
      borderRadius: 19,
    },
    parent_contaier_bottomsheet: {
      width: '100%',
      paddingHorizontal: 30,
      paddingVertical: 25,
      justifyContent: 'center',
      alignItems: 'center',
    },
    btn_heading_black: {
      color: colors.white,
      fontSize: 14,
      letterSpacing: 1,
      fontFamily: 'Montserrat-Medium',
    },
    bottomSheet_btn_margin: {
      backgroundColor: colors.primary,
      width: '100%',
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 8,
      marginTop: 10,
    },
    container: {
      flex: 1,
      // padding: 24,
      backgroundColor: colors.blackShade_s,
    },
    primar_h1: {
      color: colors.white,
      fontFamily: 'Montserrat-Bold',
      letterSpacing: 0.2,
      fontSize: 15,
    },
    modalContainer: {
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 12,
      },
      shadowOpacity: 0.58,
      shadowRadius: 16.0,
      padding: 30,
      elevation: 24,
      height: 200,
      width: 300,
      backgroundColor: colors.blackShade_s,
      alignItems: 'center',
      alignSelf: 'center',
      justifyContent: 'center',
      marginTop: dH(240),
      borderRadius: 20,
    },
    modalContainerSmall: {
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 12,
      },
      shadowOpacity: 0.58,
      shadowRadius: 16.0,
      padding: 30,
      elevation: 24,
      height: 50,
      width: 220,
      backgroundColor: colors.blackShade_s,
      alignItems: 'center',
      alignSelf: 'center',
      justifyContent: 'center',
      marginTop: dH(50),
      marginLeft: '33%',
      borderRadius: 20,
    },
    contentContainer: {
      flex: 1,
      padding: 20,
      paddingHorizontal: 10,
      backgroundColor: colors.blackShade_s,
    },
    bottomSheetTitle: {
      fontSize: 24,
      fontWeight: '500',
    },
    close_img: {
      height: 20,
      width: 20,
      resizeMode: 'contain',
    },
    close: {
      height: 20,
      width: 20,
      resizeMode: 'contain',
    },
    outercc: {
      height: 55,
      width: '100%',
      // backgroundColor: 'red',
      alignItems: 'center',
      paddingHorizontal: 20,
      flexDirection: 'row',
    },
    black: {
      backgroundColor: colors.blackshade,
      height: 110,
      width: '100%',
      marginTop: 15,
      borderRadius: 20,
    },
    heading: {
      marginTop: dW(40),
      textAlign: 'center',
      fontFamily: 'Montserrat-Bold',
      color: colors.white,
      fontSize: dW(16),
      letterSpacing: 1,
    },
    click: {
      height: 70,
      backgroundColor: colors.blackShade_s,
      width: '100%',
      borderBottomColor: colors.white,
      borderBottomWidth: 0.3,
      flexDirection: 'row',
      paddingHorizontal: 20,
      alignItems: 'center',
    },
    img__: {
      height: 45,
      width: 45,
      resizeMode: 'cover',
      borderRadius: 22,
    },
    opac: {
      backgroundColor: 'transparent',
      width: '83%',
      marginLeft: dW(10),
    },
    list_head: {
      textAlign: 'left',
      fontFamily: 'Montserrat-SemiBold',
      color: colors.white,
      fontSize: dW(16),
      letterSpacing: 0,
    },
    list_dire: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 24,
      width: 24,
      backgroundColor: colors.orange,
      borderRadius: 12,
    },
    list_dire1: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 24,
      width: 24,
      backgroundColor: colors.transparent,
      borderWidth: 3,
      borderColor: colors.orange,
      // backgroundColor: colors.orange,
      borderRadius: 12,
    },
    list_img: {
      height: 18,
      width: 18,
      resizeMode: 'contain',
    },
    one: {
      flex: 1,
      marginTop: 10,
      backgroundColor: colors.black,
    },
    toe: {
      alignContent: 'center',
      justifyContent: 'center',
      alignItems: 'center',
    },
    image: {
      marginLeft: 20,
      borderRadius: 20,
      alignSelf: 'center',
      height: 160,
      width: '95%',
      //marginTop: -80,
      // alignItems: 'center',
      justifyContent: 'center',
      //borderColor: colors.white,
      //borderWidth: 0.3,
    },
    view: {
      height: 30,
      width: 30,
      borderRadius: 15,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
    },
    image2: {
      // marginLeft: 20,
      borderRadius: 20,
      alignSelf: 'center',
      height: 160,
      width: '100%',
      //marginTop: -80,
      // alignItems: 'center',
      justifyContent: 'center',
      //borderColor: colors.white,
      //borderWidth: 0.3,
    },
    flex_90: {
      flexDirection: 'row',
      width: '90%',
      marginTop: dW(90),
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    prog: {
      textAlign: 'left',
      marginLeft: 20,
      fontFamily: 'Montserrat-Bold',
      color: colors.white,
      fontSize: dW(16),
      //letterSpacing: 1,
    },
    outer_h1: {
      width: '90%',
      // marginTop: dW(5),
      textAlign: 'center',
      fontFamily: 'Montserrat-Bold',
      color: colors.white,
      fontSize: dW(13),
      letterSpacing: 0,
    },
    outer_img: {
      height: 20,
      width: 20,
      resizeMode: 'contain',
      transform: [{rotate: '90deg'}],
    },
    tt_cc: {
      backgroundColor: colors.blackShade_s,
      borderRadius: 20,
      marginLeft: dW(130),
      height: 50,
    },
    item_heading: {
      textAlign: 'left',
      fontFamily: 'Montserrat-Bold',
      color: colors.white,
      fontSize: dW(20),
      letterSpacing: 0.5,
    },
    SportList_cc: {
      height: 100,
      width: '100%',
      marginTop: 10,
      borderRadius: 5,
      borderWidth: 1,
      borderColor: colors.white,
    },
    sl_img1: {
      height: 98,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    sl_img: {
      height: 98,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    editProfile_heading: {
      color: colors.white,
      fontSize: 15,
      fontFamily: 'Montserrat-Medium',
      marginLeft: 10,
    },
    img_10_10: {
      height: 14,
      width: 14,
      resizeMode: 'cover',
      // marginLeft: 10,
    },
    profile_img: {
      height: 28,
      width: 28,
      resizeMode: 'cover',
      marginLeft: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tt_cc1: {
      borderBottomColor: 'white',
      alignItems: 'center',
      flexDirection: 'row',
    },
    tt_btn: {
      marginTop: 3,
      /// padding: 10,
      backgroundColor: colors.blackShade_s,
      width: dW(160),
      borderRadius: 20,
    },
    linearGradient: {
      height: 48,
      width: '100%',
      paddingLeft: 15,
      paddingRight: 15,
      alignContent: 'center',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 20,
    },
    buttonText: {
      fontSize: 18,
      fontFamily: 'Gill Sans',
      textAlign: 'center',
      margin: 10,
      color: 'blue',
      backgroundColor: 'red',
    },
    sender_img: {height: 30, width: 30, borderRadius: 15, marginTop: 8},
    left_msg_c: {
      flexDirection: 'row',
      marginTop: 20,
      paddingRight: 90,
      //backgroundColor: 'white',
      // padding: 10,
    },
    left_msg_c_c: {
      flexDirection: 'row',
      // marginTop: 20,
      backgroundColor: 'white',
      padding: 15,
      marginLeft: 10,
      borderRadius: 10,
    },
    left_msg_time: {
      color: colors.primary,
      marginLeft: 10,
      marginTop: 3,
      fontSize: 12,
    },
    left_msg: {
      marginLeft: 10,
      marginTop: 3,
      fontSize: 12,
      color: colors.white,
    },

    right_msg_c: {
      flexDirection: 'row',
      alignSelf: 'flex-end',
      marginTop: 20,
      paddingLeft: 90,
      // backgroundColor: '#863BC0',
    },
    right_msg_c_c: {
      alignSelf: 'flex-end',
      alignItems: 'flex-end',
      borderRadius: 10,
      backgroundColor: '#863BC0',

      padding: 15,
      marginRight: 10,
    },
    right_msg_text: {
      color: colors.white,
      marginRight: 10,
      marginTop: 0,
      fontSize: 12,
    },
    right_msg: {
      marginRight: 10,
      marginTop: 0,
      fontSize: 12,
      borderRadius: 10,
    },
    PrimaryHeader_C: {
      height: 65,
      paddingHorizontal: 10,
      flexDirection: 'row',
      width: '100%',
      alignItems: 'center',
      justifyContent: 'space-between',
      //    backgroundColor: 'red',
    },
    PrimaryHeader_Click: {justifyContent: 'center', height: 55, width: 55},
    img_22_22: {height: 22, width: 22},
    img_2_22: {height: 51, width: 51, marginRight: 20},
    img_2_221: {height: 120, width: 120, marginTop: 30, marginRight: 20},
    tooltip: {
      backgroundColor: colors.blackShade_s,
      borderRadius: 20,
      marginLeft: dW(130),
      height: 50,
    },
    tt_c: {
      marginTop: 3,
      /// padding: 10,
      backgroundColor: colors.blackShade_s,
      width: dW(160),
      borderRadius: 20,
    },
    opa: {
      borderBottomColor: 'white',
      alignItems: 'center',
      flexDirection: 'row',
    },
    back: {
      height: 28,
      width: 28,
      resizeMode: 'cover',
      marginLeft: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    profile_v: {
      height: 55,
      marginTop: 10,
      borderBottomColor: colors.gray,
      borderBottomWidth: 0.3,
      alignItems: 'center',
      flexDirection: 'row',
      paddingHorizontal: 20,
    },
    pro_img: {
      height: 24,
      width: 24,
      resizeMode: 'contain',
      marginLeft: 10,
    },
    pro_h1: {
      color: colors.white,
      fontSize: 15,
      fontFamily: 'Montserrat-Medium',
      marginTop: 2,
      marginLeft: 10,
    },
    headingd: {
      textAlign: 'center',
      fontFamily: 'Montserrat-Bold',
      color: colors.primary,
      fontSize: dW(16),
      letterSpacing: 1,
    },
    SecButton: {
      alignItems: 'center',
      justifyContent: 'center',
      width: windowWidth() - 30,
      marginTop: dH(20),
      height: 48,
      borderRadius: 26,
      backgroundColor: colors.white,
    },
    imagess: {
      height: 14,
      width: 14,
      resizeMode: 'cover',
      // marginLeft: 10,
    },
    edit: {
      color: colors.white,
      fontSize: 15,
      fontFamily: 'Montserrat-Medium',
      // marginTop: 2,
      marginLeft: 10,
    },
    dot: {flex: 0.1, alignItems: 'center'},
    menu: {
      height: 20,
      width: 20,
      resizeMode: 'contain',
      transform: [{rotate: '90deg'}],
    },
    bottom: {
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: colors.white,
      borderWidth: 2,
      height: 30,
      width: 30,
      borderRadius: 15,
      marginTop: 8,
    },
    bottom_img: {
      height: dH(18),
      resizeMode: 'contain',
      width: dW(18),
      //tintColor: color,
    },
    laeg: {flexDirection: 'row', justifyContent: 'space-between'},
    explore: {
      //marginTop: dW(5),
      textAlign: 'left',
      marginLeft: 15,
      fontFamily: 'Montserrat-Bold',
      color: colors.white,
      fontSize: dW(19),
      letterSpacing: 0,
    },
    // close: {
    //   alignItems: 'center',
    //   height: 50,
    //   width: 50,
    //   marginTop: -10,
    //   justifyContent: 'center',
    // },
    // close_img: {
    //   height: 25,
    //   width: 25,
    //   resizeMode: 'contain',
    //   tintColor: colors.white,
    // },
    ath_type: {
      backgroundColor: colors.blackshade,
      height: 50,
      width: '100%',
      marginTop: 15,
      borderRadius: 30,
      // paddingHorizontal: 20,
      justifyContent: 'center',
    },
    ath_type_backimg: {
      backgroundColor: colors.blackshade,
      height: 50,
      width: '100%',
      //  marginTop: 15,
      borderRadius: 30,
      paddingHorizontal: 0,
      justifyContent: 'center',
    },
    ath_h1: {
      textAlign: 'left',
      fontFamily: 'Montserrat-SemiBold',
      color: colors.white,
      fontSize: dW(14),
      marginLeft: 20,
      letterSpacing: 1,
    },
    boxview: {
      height: 55,
      marginTop: 10,
      width: '100%',
      backgroundColor: colors.blackshade,
      borderRadius: 10,
      paddingHorizontal: 20,
      alignItems: 'center',
      flexDirection: 'row',
    },
    box_heading: {
      //marginTop: dW(5),
      textAlign: 'left',
      marginLeft: 12,
      fontFamily: 'Montserrat-SemiBold',
      color: colors.white,
      fontSize: dW(13),
      letterSpacing: 0,
    },
    em_img: {
      height: 20,
      width: 20,
      resizeMode: 'contain',
      alignSelf: 'flex-end',
    },
    tl: {
      height: 60,
      width: '100%',
      marginTop: 10,
      //  borderBottomWidth: 2,
      borderBottomWidth: 0.6,
      borderBottomColor: colors.white,
      padding: 5,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    tl_img: {
      height: 39,
      width: 39,
      borderRadius: 20,
      borderColor: colors.white,
      borderWidth: 1,
    },
    savan: {
      color: colors.white,
      marginLeft: 10,
      fontFamily: 'Montserrat-SemiBold',
    },
    primary: {
      alignItems: 'center',
      justifyContent: 'center',
      width: windowWidth() - 30,
      marginTop: dH(20),
      height: 48,
      borderRadius: 26,
      backgroundColor: colors.primary,
    },
    primary_h1: {
      textAlign: 'center',
      fontFamily: 'Montserrat-Bold',
      color: colors.white,
      fontSize: dW(16),
      letterSpacing: 1,
    },

    em_click: {
      height: 35,
      flexDirection: 'row',
      alignItems: 'center',
      // marginTop: 15,
      width: '100%',
    },
    clickview: {
      height: 40,
      width: 40,
      backgroundColor: '#FF9900',
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
    },
    message: {
      color: colors.white,
      marginLeft: 10,
      fontFamily: 'Montserrat-SemiBold',
    },
    white_click: {
      height: 35,
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 15,
    },
    white_v: {
      height: 40,
      width: 40,
      backgroundColor: '#FF6767',
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
    },
    clickviewimg: {height: 20, width: 20, resizeMode: 'contain'},
    edit_ath: {
      color: colors.white,
      marginLeft: 10,
      fontFamily: 'Montserrat-SemiBold',
    },
    sig: {
      width: '100%',
      height: 35,
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 15,
    },
    sig1: {
      height: 40,
      width: 40,
      backgroundColor: '#681FA1',
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
    },
  });
};
export default useStyle;
