import {StyleSheet} from 'react-native';
import {
  dW,
  dH,
  windowHeight,
  windowWidth,
} from '../../utils/dynamicHeightWidth';
import assets from '../../assests/images/index';
import colors from '../../constants/colors';
const useStyle = () => {
  return StyleSheet.create({
    center: {
      alignContent: 'center',
      justifyContent: 'center',
      alignItems: 'center',
    },
    downarrow: {height: 10, width: 10, resizeMode: 'contain', marginLeft: 6},
    today: {
      //marginTop: dW(7),
      textAlign: 'left',
      marginLeft: 20,
      fontFamily: 'Montserrat-Bold',
      color: colors.white,
      fontSize: dW(16),
      letterSpacing: 1,
      lineHeight: 21,
    },
    blackv: {
      alignSelf: 'flex-end',
      margin: 15,
      height: 30,
      paddingHorizontal: 15,
      backgroundColor: colors.black,
      borderRadius: 5,
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
    },
    start: {
      width: '90%',
      // marginTop: dW(5),
      textAlign: 'left',
      marginLeft: 20,
      fontFamily: 'Montserrat-SemiBold',
      color: colors.white,
      fontSize: dW(12),
      letterSpacing: 0,
      lineHeight: 23,
    },
    manfoot: {
      marginRight: 20,
      marginLeft: 20,
      borderRadius: 10,
      alignSelf: 'center',
      height: 160,
      width: '91%',
      marginTop: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    foot: {
      //marginRight: 10,
      borderRadius: 10,
      // alignItems: 'center',
      justifyContent: 'center',
      height: 160,
      width: '100%',
      // marginTop: -80,
    },
    header_img: {height: 200, width: '100%'},
    imageBack: {
      width: '100%',
      height: '100%',
    },
    partition: {
      height: 1,
      width: '100%',
      backgroundColor: colors.blackShade_s,
    },
    h4: {
      margin: dW(20),
      textAlign: 'left',
      fontFamily: 'Montserrat-Regular',
      color: colors.white,
      fontSize: dW(13),
      letterSpacing: 0,
    },
    img_25_25: {height: 25, width: 25, resizeMode: 'contain'},
    h3: {
      marginLeft: dW(10),
      textAlign: 'left',
      fontFamily: 'Montserrat-Regular',
      color: colors.white,
      fontSize: dW(15),
      letterSpacing: 0,
    },
    img_15_15: {height: 15, width: 15, resizeMode: 'contain'},
    main_cc: {
      flexDirection: 'row',
      flex: 1,
      height: 30,
      paddingHorizontal: 20,
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    h2: {
      width: '90%',
      margin: dW(20),
      textAlign: 'left',
      fontFamily: 'Montserrat-Bold',
      color: colors.white,
      fontSize: dW(15),
      letterSpacing: 0,
    },
    h1: {
      width: '90%',
      margin: dW(20),
      textAlign: 'left',
      fontFamily: 'Montserrat-Regular',
      color: colors.white,
      fontSize: dW(15),
      letterSpacing: 0,
    },
  });
};
export default useStyle;
